name: PR

on:
  pull_request:
    branches:
      - 'main'
      
env:
  POETRY_VERSION: 1.4.2
  
jobs:
  checks-nisdc:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Check for lock changes (nisdc)
        run: poetry lock --check
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install nisdc
        run: poetry install -v
      - name: Lint nisdc
        run: poetry run ni-python-styleguide lint
  