name:  Update docs and Publish NIMS

on:
  release:
    types: [released]

concurrency: publish_to_pypi

env:
  # Versions are also listed in PR.yml
  POETRY_VERSION: 1.4.2
  PYTHON_VERSION: 3.9

jobs:
  build:
    name: Publish NIMS Package to PyPI
    runs-on : ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Check for lock changes
        run: poetry lock --check

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Setup NIMS
        run: poetry install

      - name: Lint NIMS
        run: poetry run ni-python-styleguide lint

      # If the tag is 0.1.0, this will set the version of NIMS package to 0.1.0
      - name: Store version from Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Update NIMS package version based on tag name.
        run: |
          poetry version ${{ steps.vars.outputs.tag }}

      - name: Setup NIMS with docs
        run: poetry install --with docs

      # To Test the Publish use : poetry publish --build --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }} -r test-pypi
      - name: Build NIMS Python package and publish to PyPI
        if: ${{ startsWith(github.event.release.target_commitish, 'main') }}
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: NIMS Artifacts
          path: dist/ # path/to/artifact